// <auto-generated />
using DetailPage.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace DetailPage.Migrations
{
    [DbContext(typeof(DetailPageContext))]
    [Migration("20180320084757_changeColumnLength")]
    partial class changeColumnLength
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DetailPage.Models.DetailPageModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("HtmlContent");

                    b.Property<string>("Name")
                        .HasMaxLength(30);

                    b.Property<string>("Remark")
                        .HasMaxLength(400);

                    b.Property<string>("Url")
                        .HasMaxLength(1000);

                    b.HasKey("ID");

                    b.ToTable("DetailPage");
                });
#pragma warning restore 612, 618
        }
    }
}
